In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data2.csv')

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [5]:
df['Actor'][3]

'Ranbir Kapoor'

In [7]:
type(df['Actor'])

pandas.core.series.Series

In [9]:
df[['Actor','IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [10]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [13]:
df.loc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [14]:
df.iloc[1]

Actor                       Salman Khan
Film                    Tiger Zinda Hai
Year                               2017
Genre                            Action
BoxOffice(INR Crore)                565
IMDb                                6.0
Name: 1, dtype: object

In [15]:
df.loc[8,'IMDb']

7.0

In [16]:
df.loc[7,'IMDb']

6.5

In [17]:
df.iloc[7,5]

6.5

In [19]:
df.loc[0:3,["Actor","IMDb","Film"]]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal
3   Ranbir Kapoor   5.6       Brahmastra

In [21]:
df.iloc[0:3,0:3]

            Actor             Film  Year
0  Shah Rukh Khan          Pathaan  2023
1     Salman Khan  Tiger Zinda Hai  2017
2      Aamir Khan           Dangal  2016

In [22]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [23]:
df.iat[0,0]

'Shah Rukh Khan'

In [27]:
df[df['IMDb']>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [28]:
df[df['IMDb']>6]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [32]:
df[(df['IMDb']>6) & (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [33]:
df[(df['IMDb']>6) | (df['Year']>2018)]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [36]:
df.query("Year>2018 and IMDb>6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2